/**
 * Original word list for Cipher Grid: common English nouns with plenty of
 * double meanings, so clues can bridge several cards at once.
 */
export const WORDS: readonly string[] = [
  // everyday objects
  'ANCHOR', 'BACKPACK', 'BALLOON', 'BASKET', 'BLANKET', 'BUCKET', 'CANDLE', 'COMPASS', 'CURTAIN', 'CUSHION',
  'ENVELOPE', 'FEATHER', 'HAMMER', 'HELMET', 'KETTLE', 'LADDER', 'LANTERN', 'MAGNET', 'MIRROR', 'NAPKIN',
  'PENCIL', 'PILLOW', 'PUZZLE', 'RIBBON', 'ROPE', 'SADDLE', 'SCISSORS', 'SHOVEL', 'SPONGE', 'STAPLER',
  'SUITCASE', 'TICKET', 'TOWEL', 'TROPHY', 'UMBRELLA', 'WALLET', 'WHISTLE', 'WRENCH', 'ZIPPER', 'BLENDER',
  // places
  'AIRPORT', 'ATTIC', 'BAKERY', 'BALCONY', 'BARN', 'BASEMENT', 'CABIN', 'CANYON', 'CASTLE', 'CAVE',
  'CHAPEL', 'CLINIC', 'COTTAGE', 'DESERT', 'DUNGEON', 'FACTORY', 'FARM', 'FOUNTAIN', 'GARAGE', 'GARDEN',
  'GLACIER', 'HARBOR', 'HIGHWAY', 'ISLAND', 'JUNGLE', 'KITCHEN', 'LIGHTHOUSE', 'MARKET', 'MEADOW', 'MUSEUM',
  'OASIS', 'ORCHARD', 'PALACE', 'PRISON', 'RANCH', 'REEF', 'STUDIO', 'SWAMP', 'TUNNEL', 'VOLCANO',
  // nature & weather
  'AVALANCHE', 'BLIZZARD', 'BREEZE', 'CLOUD', 'COMET', 'CRYSTAL', 'DAWN', 'ECLIPSE', 'FOG', 'FROST',
  'GRAVITY', 'HURRICANE', 'LAVA', 'LIGHTNING', 'METEOR', 'MIST', 'PEBBLE', 'PLANET', 'RAINBOW', 'RIVER',
  'SAND', 'SHADE', 'STORM', 'SUNSET', 'THUNDER', 'TIDE', 'TORNADO', 'TWILIGHT', 'VALLEY', 'WATERFALL',
  // animals
  'BADGER', 'BEAVER', 'BEETLE', 'BISON', 'CAMEL', 'CHEETAH', 'COBRA', 'CRAB', 'CROW', 'DOLPHIN',
  'DONKEY', 'FALCON', 'FERRET', 'FLAMINGO', 'FOX', 'GECKO', 'GOAT', 'GORILLA', 'HAMSTER', 'HEDGEHOG',
  'HERON', 'HYENA', 'JAGUAR', 'JELLYFISH', 'KOALA', 'LEOPARD', 'LIZARD', 'LOBSTER', 'MOOSE', 'MOTH',
  'OTTER', 'OWL', 'OYSTER', 'PANDA', 'PARROT', 'PEACOCK', 'PELICAN', 'PIGEON', 'PYTHON', 'RACCOON',
  'RAVEN', 'RHINO', 'SALMON', 'SEAGULL', 'SLOTH', 'SPARROW', 'SQUID', 'SWAN', 'TIGER', 'TOAD',
  'TURTLE', 'VULTURE', 'WALRUS', 'WASP', 'WEASEL', 'WOLF', 'WOMBAT', 'YAK', 'ZEBRA', 'ANT',
  // food & drink
  'ALMOND', 'BACON', 'BAGEL', 'BISCUIT', 'BUTTER', 'CABBAGE', 'CARAMEL', 'CEREAL', 'CHEESE', 'CHERRY',
  'CHILI', 'CINNAMON', 'COCONUT', 'COFFEE', 'CUCUMBER', 'DONUT', 'DUMPLING', 'GARLIC', 'GINGER', 'GRAPE',
  'MANGO', 'MUFFIN', 'MUSHROOM', 'MUSTARD', 'NOODLE', 'OLIVE', 'ONION', 'PANCAKE', 'PEACH', 'PEANUT',
  'PEPPER', 'PICKLE', 'PIZZA', 'POPCORN', 'PRETZEL', 'PUDDING', 'RADISH', 'SALAD', 'SANDWICH', 'SAUSAGE',
  'SOUP', 'SPINACH', 'SUSHI', 'SYRUP', 'TACO', 'TOAST', 'TOFFEE', 'VANILLA', 'WAFFLE', 'YOGURT',
  // people & roles
  'ACROBAT', 'ARCHER', 'ASTRONAUT', 'BAKER', 'BARBER', 'BUTLER', 'CAPTAIN', 'CHAMPION', 'CLOWN', 'COWBOY',
  'DETECTIVE', 'DIVER', 'DRUMMER', 'EMPEROR', 'FARMER', 'FIREFIGHTER', 'GLADIATOR', 'GOALIE', 'HERMIT', 'HUNTER',
  'JESTER', 'JUDGE', 'LIBRARIAN', 'MAGICIAN', 'MAYOR', 'MERMAID', 'MONK', 'PILGRIM', 'PLUMBER', 'POET',
  'PROFESSOR', 'REFEREE', 'SAILOR', 'SCULPTOR', 'SHERIFF', 'SURGEON', 'TAILOR', 'VAMPIRE', 'WIZARD', 'ZOMBIE',
  // transport & tech
  'ANTENNA', 'BATTERY', 'BICYCLE', 'CANOE', 'CIRCUIT', 'DRONE', 'ELEVATOR', 'ESCALATOR', 'FERRY', 'GLIDER',
  'HEADPHONES', 'KEYBOARD', 'LAPTOP', 'MICROPHONE', 'MOTORCYCLE', 'PIXEL', 'PODCAST', 'PRINTER', 'RADAR', 'ROCKET',
  'SCOOTER', 'SKATEBOARD', 'SLED', 'SPEAKER', 'SUBMARINE', 'TRACTOR', 'TRAM', 'TROLLEY', 'WAGON', 'YACHT',
  // sports & games
  'ARENA', 'BOWLING', 'CHESS', 'DART', 'DOMINO', 'FENCING', 'GOLF', 'GYMNAST', 'HOCKEY', 'JAVELIN',
  'JOKER', 'KARATE', 'KAYAK', 'MARATHON', 'MEDAL', 'PADDLE', 'PUCK', 'RUGBY', 'SKI', 'SLEDGE',
  'SNORKEL', 'SOCCER', 'SURF', 'TENNIS', 'TRAMPOLINE', 'VOLLEYBALL', 'WRESTLER', 'YOGA', 'DICE', 'GOAL',
  // body, clothing & abstract
  'ANKLE', 'BEARD', 'ELBOW', 'FIST', 'FRECKLE', 'KNEE', 'MUSTACHE', 'SHOULDER', 'SKULL', 'WRIST',
  'APRON', 'BOOTS', 'CLOAK', 'CROWN', 'GOWN', 'HOODIE', 'JACKET', 'MITTEN', 'SCARF', 'SNEAKER',
  'ALARM', 'BUBBLE', 'ECHO', 'FLAME', 'GHOST', 'HONEY', 'JEWEL', 'KEYHOLE', 'MAZE', 'MELODY',
  'MYSTERY', 'NEEDLE', 'ORBIT', 'PIRATE', 'QUEST', 'RIDDLE', 'SECRET', 'SHIELD', 'SPARK', 'SPIRAL',
  'STATUE', 'TATTOO', 'THRONE', 'TREASURE', 'VELVET', 'VILLAIN', 'WHISPER', 'WIZARDRY', 'YARN', 'ZODIAC',
  // more double-meaning favourites
  'BRIDGE', 'CHEST', 'CRANE', 'DRAFT', 'FAN', 'MATCH', 'MINT', 'NOTE', 'PALM', 'PITCH',
  'PLANT', 'POOL', 'RULER', 'SCALE', 'SEAL', 'SPRING', 'STAMP', 'TRUNK', 'WAVE', 'WELL',
];
